# Generated by Django 4.1.4 on 2023-01-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_completion',
            field=models.DateField(),
        ),
    ]
