# Generated by Django 4.1.4 on 2023-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_application_date_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Received', max_length=20),
        ),
    ]
