# Generated by Django 4.1.4 on 2023-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
