# Generated by Django 4.1.4 on 2023-01-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_clientprofile_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='FrelancerExperience',
        ),
    ]
