# Generated by Django 4.1.4 on 2023-01-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_experience_frelancerexperience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrelancerExperience',
            new_name='FreelancerExperience',
        ),
    ]
